(let ([x (+ 10 12)])
  (let ([x (+ x 12)])
    (let ([x (+ x 12)])
      (let ([x (+ x 12)])
        (let ([x (+ x 12)])
          (let ([x (+ x 12)])
            (let ([x (+ x 12)])
              (let ([x (+ x 12)])
                (let ([x (+ x 12)])
                  (let ([x (+ x 12)])
                    (let ([x (+ x 12)])
                      (let ([x (+ x 12)])
                        (let ([x (+ x 12)])
                          (let ([x (+ x 12)])
                            (let ([x (+ x 12)])
                              (let ([x (+ x 12)])
                                (let ([x (+ x 12)])
                                  (let ([x (+ x 12)])
                                    x)
                                  x)
                                x)
                              x)
                            x)
                          x)
                        x)
                      x)
                    x)
                  x)
                x)
              x)
            x)
          x)
        x)
      x)
    x)
  x)